[package]
name = "srn-server"
version = "0.1.0"
authors = ["Valeriy Kuzmin <malcoriel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
