[package]
name = "srn-server"
version = "0.1.0"
authors = ["Valeriy Kuzmin <malcoriel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1"
lazy_static = "1.4.0"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
rocket_cors = "0.5.2"
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.60"
tokio = "0.1"
websocket = "0.26.2"
