[debug]
address = "127.0.0.1"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
limits = { forms = 32768 }
secret_key = "SiKyMvjeqLSVdAIUfGNE2xBsDP/cVekDuhTScWA6RO4="
